export const LIST_BANNER_PHIM = "LIST_BANNER_PHIM";
export const LIST_MENU_PHIM = "LIST_MENU_PHIM";
export const SET_PHIM_DANG_CHIEU = "SET_PHIM_DANG_CHIEU";
export const SET_PHIM_SAP_CHIEU = "SET_PHIM_SAP_CHIEU";
